import {
  ADMIN_ROLES,
  DEAN_ROLES,
  DIRECTOR_ROLES,
  FACULTY_ROLES,
  HOD_ROLES,
  STUDENT_ROLES,
} from "../../ui/nav/roles";

export const THESIS_BASE = "/thesis-research";

const isPhd = ({ programmeType }) => programmeType === "PHD";
const isPg = ({ programmeType }) => programmeType === "PG";
const isResearchStudent = ({ programmeType }) =>
  programmeType && programmeType !== "UG";

export const THESIS_PAGES = [
  {
    key: "studentThesis",
    slug: "thesis-supervisor-registration",
    title: "Supervisor Registration",
    icon: "UserFocus",
    group: "Thesis",
    roles: STUDENT_ROLES,
    when: isResearchStudent,
  },
  {
    key: "studentThesisSubmissionPhd",
    slug: "final-submission",
    title: "Final Submission",
    icon: "Signature",
    group: "Thesis",
    roles: STUDENT_ROLES,
    when: isPhd,
  },
  {
    key: "studentThesisSubmissionPg",
    slug: "thesis-submission",
    title: "Thesis Submission",
    icon: "Signature",
    group: "Thesis",
    roles: STUDENT_ROLES,
    when: isPg,
  },
  {
    key: "studentComprehensiveExam",
    slug: "comprehensive-examination",
    title: "Comprehensive Examination",
    icon: "ListChecks",
    group: "Milestones",
    roles: STUDENT_ROLES,
    when: isResearchStudent,
  },
  {
    key: "studentProgressSeminar",
    slug: "progress-seminar",
    title: "Progress Seminar",
    icon: "ChatCircleDots",
    group: "Milestones",
    roles: STUDENT_ROLES,
    when: isResearchStudent,
  },
  {
    key: "studentOpenSeminar",
    slug: "open-seminar",
    title: "Open Seminar",
    icon: "Megaphone",
    group: "Milestones",
    roles: STUDENT_ROLES,
    when: isResearchStudent,
  },
  {
    key: "studentTeachingCredit",
    slug: "teaching-credit",
    title: "Teaching Credit",
    icon: "ChalkboardTeacher",
    group: "Milestones",
    roles: STUDENT_ROLES,
    when: isResearchStudent,
  },

  {
    key: "supervisorDashboard",
    slug: "thesis-review",
    title: "Thesis Review",
    icon: "UserFocus",
    group: "Supervision",
    roles: FACULTY_ROLES,
  },
  {
    key: "supervisorComprehensiveExam",
    slug: "comprehensive-exam",
    title: "Comprehensive Exam",
    icon: "ListChecks",
    group: "Supervision",
    roles: FACULTY_ROLES,
  },
  {
    key: "supervisorThesisGrading",
    slug: "thesis-grading",
    title: "Thesis Grading",
    icon: "Stamp",
    group: "Supervision",
    roles: FACULTY_ROLES,
  },
  {
    key: "supervisorTeachingCredit",
    slug: "teaching-credit",
    title: "Teaching Credit",
    icon: "ChalkboardTeacher",
    group: "Supervision",
    roles: FACULTY_ROLES,
  },
  {
    key: "rpcDashboard",
    slug: "rpc-seminar-review",
    title: "RPC / Seminar Review",
    icon: "ChatCircleDots",
    group: "Seminars",
    roles: FACULTY_ROLES,
  },
  {
    key: "supervisorOpenSeminar",
    slug: "open-seminar",
    title: "Open Seminar",
    icon: "Megaphone",
    group: "Seminars",
    roles: FACULTY_ROLES,
  },
  {
    key: "deanNomineeReports",
    slug: "dean-nominee-reports",
    title: "Dean Nominee Reports",
    icon: "FileText",
    group: "Seminars",
    roles: FACULTY_ROLES,
  },
  {
    key: "supervisorSubmissionPanel",
    slug: "examiner-assignment",
    title: "Examiner Assignment",
    icon: "UserPlus",
    group: "Examiners",
    roles: FACULTY_ROLES,
  },
  {
    key: "supervisorReviewReports",
    slug: "examiner-reports",
    title: "Examiner Reports",
    icon: "Receipt",
    group: "Examiners",
    roles: FACULTY_ROLES,
  },
  {
    key: "thesisRevisionRpc",
    slug: "thesis-revision-rpc",
    title: "Thesis Revision RPC",
    icon: "ChatCircleDots",
    group: "Examiners",
    roles: FACULTY_ROLES,
  },

  {
    key: "hodDashboard",
    slug: "thesis-review",
    title: "Thesis Review",
    icon: "UserFocus",
    group: null,
    roles: HOD_ROLES,
  },
  {
    key: "hodComprehensiveExam",
    slug: "comprehensive-exam",
    title: "Comprehensive Exam",
    icon: "ListChecks",
    group: null,
    roles: HOD_ROLES,
  },
  {
    key: "hodOpenSeminar",
    slug: "open-seminar",
    title: "Open Seminar",
    icon: "Megaphone",
    group: null,
    roles: HOD_ROLES,
  },
  {
    key: "hodTeachingCredit",
    slug: "teaching-credit",
    title: "Teaching Credit",
    icon: "ChalkboardTeacher",
    group: null,
    roles: HOD_ROLES,
  },
  {
    key: "hodExaminerPanel",
    slug: "pg-examiner-panel",
    title: "PG Examiner Panel",
    icon: "Users",
    group: null,
    roles: HOD_ROLES,
  },

  {
    key: "deanDashboard",
    slug: "thesis-approval",
    title: "Thesis Approval",
    icon: "CheckCircle",
    group: null,
    roles: DEAN_ROLES,
  },
  {
    key: "deanComprehensiveExam",
    slug: "comprehensive-exam",
    title: "Comprehensive Exam",
    icon: "ListChecks",
    group: null,
    roles: DEAN_ROLES,
  },
  {
    key: "deanOpenSeminar",
    slug: "open-seminar",
    title: "Open Seminar",
    icon: "Megaphone",
    group: null,
    roles: DEAN_ROLES,
  },
  {
    key: "deanPanelDashboard",
    slug: "examiner-panel",
    title: "Examiner Panel",
    icon: "Users",
    group: null,
    roles: DEAN_ROLES,
  },
  {
    key: "deanPgExaminerPanel",
    slug: "pg-examiner-panel",
    title: "PG Examiner Panel",
    icon: "UsersThree",
    group: null,
    roles: DEAN_ROLES,
  },

  {
    key: "directorDashboard",
    slug: "examiner-prioritization",
    title: "Examiner Prioritization",
    icon: "ListNumbers",
    group: null,
    roles: DIRECTOR_ROLES,
  },

  {
    key: "adminThesisGrades",
    slug: "thesis-grades",
    title: "Thesis Grades",
    icon: "Stamp",
    group: null,
    roles: ADMIN_ROLES,
  },
  {
    key: "adminComprehensiveEligibility",
    slug: "comprehensive-exam-eligibility",
    title: "Comprehensive Exam Eligibility",
    icon: "UserCheck",
    group: null,
    roles: ADMIN_ROLES,
  },
  {
    key: "adminTeachingCredit",
    slug: "teaching-credit",
    title: "Teaching Credit",
    icon: "ChalkboardTeacher",
    group: null,
    roles: ADMIN_ROLES,
  },
  {
    key: "adminHonorarium",
    slug: "examiner-honorarium",
    title: "Examiner Honorarium",
    icon: "Money",
    group: null,
    roles: ADMIN_ROLES,
  },
];
