import { host } from "../globalRoutes";

const iwdBaseRoute = `${host}/iwdModuleV2/api`;

export const fetchDesignationsRoute = `${iwdBaseRoute}/fetch-designations/`;
export const createRequestRoute = `${iwdBaseRoute}/create-request/`;
export const createdRequestsRoute = `${iwdBaseRoute}/created-requests/`;
export const requestsStatusRoute = `${iwdBaseRoute}/requests-status/`;
export const directorApprovedRequestsRoute = `${iwdBaseRoute}/director-approved-requests/`;
export const issueWorkOrderRoute = `${iwdBaseRoute}/issue-work-order/`;
export const workUnderProgressRoute = `${iwdBaseRoute}/work-under-progress/`;
export const workCompletedRoute = `${iwdBaseRoute}/work-completed/`;
export const viewBudgetRoute = `${iwdBaseRoute}/view-budget/`;
export const addBudgetRoute = `${iwdBaseRoute}/add-budget/`;
export const editBudgetRoute = `${iwdBaseRoute}/edit-budget/`;
export const deanPendingRequestsRoute = `${iwdBaseRoute}/dean-pending-requests/`;
export const deanProcessedRequestsRoute = `${iwdBaseRoute}/dean-processed-requests/`;
export const handleDirectorApprovalRoute = `${iwdBaseRoute}/handle-director-approval/`;
export const auditDocumentViewRoute = `${iwdBaseRoute}/audit-document-view/`;
export const auditDocumentRoute = `${iwdBaseRoute}/audit-document/`;
export const settleBillsViewRoute = `${iwdBaseRoute}/settle-bills-view/`;
export const settleBillRoute = `${iwdBaseRoute}/handle-settle-bill-request/`;
export const engineerProcessedRequestsRoute = `${iwdBaseRoute}/engineer-processed-requests/`;
export const handleAdminApprovalRoute = `${iwdBaseRoute}/handle-admin-approval/`;
export const createProposalRoute = `${iwdBaseRoute}/create-proposal/`;
export const getProposalsRoute = `${iwdBaseRoute}/get-proposals/`;
export const getItemsRoute = `${iwdBaseRoute}/get-items/`;
export const issuedWorkRoute = `${iwdBaseRoute}/issued-work/`;
export const handleBillGeneratedRequestsRoute = `${iwdBaseRoute}/handle-bill-generated-requests/`;
export const generatedBillsViewRoute = `${iwdBaseRoute}/generated-bills-view/`;
export const handleProcessBillsRoute = `${iwdBaseRoute}/handle-process-bills/`;
export const generateBillPdfRoute = `${iwdBaseRoute}/generate-bill-pdf/`;
export const viewFileRoute = `${iwdBaseRoute}/view-file/`;
export const forwardRequestRoute = `${iwdBaseRoute}/forward-request/`;
export const handleDeanProcessRequestRoute = `${iwdBaseRoute}/handle-dean-process-request/`;
export const rejectedRequestsRoute = `${iwdBaseRoute}/rejected-requests-view/`;
export const handleUpdateRequestsRoute = `${iwdBaseRoute}/handle-update-requests/`;
export const requestsInProgressRoute = `${iwdBaseRoute}/requests-in-progress/`;
export const addVendorRoute = `${iwdBaseRoute}/add-vendor/`;
export const getWorkRoute = `${iwdBaseRoute}/get-work/`;
export const getVendorsRoute = `${iwdBaseRoute}/get-vendors/`;

// ===== NEW SLA & INVENTORY ENDPOINTS (UC-29, UC-30, UC-31) =====
export const slaDashboardRoute = `${iwdBaseRoute}/sla-dashboard/`;
export const inventoryItemsRoute = `${iwdBaseRoute}/inventory-items/`;
export const inventoryTransactionsRoute = `${iwdBaseRoute}/inventory-transactions/`;
export const issueMaterialsRoute = `${iwdBaseRoute}/issue-materials/`;
export const receiveMaterialsRoute = `${iwdBaseRoute}/receive-materials/`;
export const feedbackHistoryRoute = `${iwdBaseRoute}/feedback-history/`;
export const submitFeedbackRoute = `${iwdBaseRoute}/submit-feedback/`;
export const reopenRequestRoute = `${iwdBaseRoute}/reopen-request/`;
export const slaEscalationsRoute = `${iwdBaseRoute}/sla-escalations/`;
